### ISSUE TITLE
Diagnose slow genotype

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/streamline-delivery#19] opened 2024-02-15 10:14 UTC
Look into what is slow

**Comment by islean** [comment] 2024-02-16 15:08
Current analysis shows:

- The code is written in a very unclear way, where multiple implicit joins are made and the response object consists of ~10 nested Pydantic BaseModels.
- Potentially one could try adding an index to sample.comment although with the current type of sample.comment (text), this is not supported in MySQL. Whether it would work or not is doubtful as well.
- A lot of calculations are done in validators of the basemodels.

Conclusion:

Much larger scope than was intended. If developers are to be happy, a rewrite of large parts (or at least the endpoints) of Genotype would be needed. Doubtful whether the fix should be included in the sprint unless some index solves it easily. Might as well not be the query which is slow though.

**Comment by islean** [comment] 2024-02-16 15:28
> Genotype is hopefully up for a modernization in the coming or next after that quarter. I think this should be solved there.

We will consider out of scope for the Streamline Delivery project for now then.

**Closed** 2024-02-19 15:49 UTC
Labels: work item, backend
